# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-05 05:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_user_email'),
        ('todolist', '0003_auto_20201104_0643'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='user',
            field=models.OneToOneField(default='0', on_delete=django.db.models.deletion.CASCADE, to='register.User'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='created',
            field=models.DateField(default=b'2020-11-05'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='due_date',
            field=models.DateField(default=b'2020-11-05'),
        ),
    ]
